version: '3.8'
services:
  webapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - kafka

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"

  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENERS: INSIDE://kafka:9093
      KAFKA_LISTENER_NAME_INSIDE: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
